version: "3"
services:
  harold:
    build: ./harold
    environment:
      - PORT=19100
      - DISCORD_TOKEN

  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
    env_file:
      - db.env

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
    env_file:
      - db.env
    depends_on:
      - db

  web:
    build: ./web
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=altaria.aamulumi.info
      - LETSENCRYPT_HOST=altaria.aamulumi.info
    depends_on:
      - app
      - proxy
    networks:
      - proxy-tier
      - default

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - omgwtfssl

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volume: 
      - /var/run/docker.sock:/tmp/docker.sock:ro
    volumes-from: proxy
    environment:
      - DEFAULT_EMAIL
    networks:
      - proxy-tier

volumes:
  nextcloud:
  db:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:
